### ISSUE TITLE
SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by dmatora** [sarcophagus-org/archaeologist-service#10]
when trying to run `go run main.go` I get 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xae07af]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/ethclient.(*Client).CodeAt(0x0, 0x11973c0, 0xc0000c0038, 0xb7fbd5b028e99b93, 0x9664817c2107faf3, 0xc046babefc, 0x0, 0xc00012bb64, 0xc00041a600, 0x14, ...)
        /root/work/pkg/mod/github.com/ethereum/go-ethereum@v1.9.25/ethclient/ethclient.go:373 +0x11f
github.com/decent-labs/airfoil-sarcophagus-archaeologist-service/shared/utility.IsContract(0xb7fbd5b028e99b93, 0x9664817c2107faf3, 0xb7fbd5b046babefc, 0x0, 0xc046babefc)
        /root/archaeologist-service/shared/utility/utility.go:35 +0x6d
github.com/decent-labs/airfoil-sarcophagus-archaeologist-service/shared/ethereum.SarcoAddress(0xc00041a5a0, 0x2a, 0x0, 0x0, 0x0, 0xc000000000, 0x1, 0x2)
        /root/archaeologist-service/shared/ethereum/ethereum.go:29 +0x80
github.com/decent-labs/airfoil-sarcophagus-archaeologist-service/shared/archaeologist.InitializeArchaeologist(0xc0000f3440, 0xc000102360, 0x6, 0xedd621, 0x2)
        /root/archaeologist-service/shared/archaeologist/initialize.go:56 +0x40d
main.main()
        /root/archaeologist-service/main.go:33 +0x250
exit status 2
```

**Comment by dmatora** [comment]
Solved by getting etc node running
